### ISSUE TITLE
[ENHANCEMENT] 1.18.2 Support

### ISSUE THREAD

**Issue by linsaftw** [Elytrium/LimboAuth#10]
Joining to the limbo with 1.18.2 on 1.16.5 server with ViaVersion just disconnects the client.

When the session is active the 1.18.2 client can play normally.

**Comment by hevav** [comment]
Have you changed "prepare version" in plugins/limboapi/config.yml?

**Comment by linsaftw** [comment]
Thank you

**Comment by linsaftw** [comment]
Reopen. LimboFilter works good but the LimboAuth limbo stucks on loading terrain.

**Comment by hevav** [comment]
Update LimboAPI

**Comment by hevav** [comment]
![image](https://user-images.githubusercontent.com/14876058/156881735-d3376eff-3ee7-4580-81e6-7bc04eeb7fc3.png)

Try setting the "Y" parameter to 256.0 here

**Comment by linsaftw** [comment]
It's done. Thanks!
