### ISSUE TITLE
[ENHANCEMENT] PasswordChangeEvent

### ISSUE THREAD

**Issue by Wgis** [Elytrium/LimboAuth#100]
**Describe the feature you'd like to have implemented**
New event PasswordChangeEvent when password changed to user.

**Is your feature request related to an existing problem? Please describe.**
It's can solve troubles with different integrations with site.

**Additional context**
Main problem is to detect when user changed password. If we can't detect, we can't update instantly. But with this event being easy update password on any site CMS.

**Comment by xlanyleeet** [comment]
Привет! Команда разработчиков, что скажете? Штука оч годная для интеграций на сайт и прочее.
