### ISSUE TITLE
Doubled nickname in tab list when online-mode-need-auth:false [BUG] 

### ISSUE THREAD

**Issue by Machitor** [Elytrium/LimboAuth#101]
**Describe the bug**
nickname doubled in tablist when online-mode-need-auth setting disabled

**To Reproduce**
1. Set 'online-mode-need-auth: ' in config to 'false'
2. Log in with premium account
3. See doubled nickname in tab list

**Server Info (please complete the following information):**
 - spigot 1.8.8 official
 - All Limbo plugins versions:

 - [limboapi-1.1.12.jar, downloaded from https://github.com/Elytrium/LimboAPI/releases/download/1.1.12/limboapi-1.1.12.jar]
 - [limboauth-1.1.12.jar, downloaded from https://github.com/Elytrium/LimboAuth/releases/download/1.1.12/limboauth-1.1.12.jar]

 - /velocity dump link [https://pastebin.com/iEwuW5Jb]
 
 no matter online or offline [velocty]

**Comment by GIGABAIT93** [comment]
I have the same problem

**Comment by GIGABAIT93** [comment]
не

> I have the same problem. But changing the online-mode-need-auth setting doesn't solve the problem for me. I use Geyser-Velocity and floodgate-velocity when floodgate-need-auth: false and remove the plugin floodgate then the duplicate nickname will disappear ![зображення](https://user-images.githubusercontent.com/59637348/248387832-63af58a6-a127-403c-be9e-6cb075b9de89.png) I think that due to this error, the plugin does not load the code that causes duplication of nicknames

also I found out that this is only for premium accounts.

**Comment by mdxd44** [comment]
if this is still happens please reopen an issue
