### ISSUE TITLE
[BUG] Players can still join if the database connection failed

### ISSUE THREAD

**Issue by comendantmc** [Elytrium/LimboAuth#11]
**Describe the bug**
If there is no connection to the database server continues to work and lets players in without the auth. This is a serious security concern

**To Reproduce**
* Stop the database
* Join the server

**Expected behavior**
The server should stop immediately

**Comment by hevav** [comment]
Done (https://github.com/Elytrium/LimboAuth/commit/35d932ddfa02e2fc5236dcf07c1606b73b6e3585)
