### ISSUE TITLE
[BUG] BE Players can't join the server

### ISSUE THREAD

**Issue by FrankHan052176** [Elytrium/LimboAuth#12]
**Describe the bug**
BE Players can't join the server

**To Reproduce**
1. a be account
2. join
3. See error

**Expected behavior**
emmmmmm

**Screenshots**
![image](https://user-images.githubusercontent.com/48244729/158048783-e770dc43-c09c-4bd3-9d81-df1cde5b1bca.png)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - [e.g. LimboAPI 1.0.4-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/1926762894]
 - [e.g. LimboAuth 1.0.3-rc3, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/1806267878]

 - /velocity dump link [e.g. https://dump.velocitypowered.com/iqefukiliq.csharp]

**Additional context**
None

**Comment by lRENyaaa** [comment]
Java 1.18.2 doesn't work either

**Comment by soup6020** [comment]
Seems to be related to LimboAPI, I'm facing a similar issue. Floodgate is seeing all players as connecting from Java and immediately disconnecting any Bedrock joins.

**Comment by mdxd44** [comment]
Fixed in the latest builds.
