### ISSUE TITLE
[BUG] Краш прокси при спаме командами на смену пароля

### ISSUE THREAD

**Issue by deHasher** [Elytrium/LimboAuth#131]
Если спамить через [этот мод например](https://www.curseforge.com/minecraft/mc-mods/command-macros) /changepass qwqwqw qwqwqw (ну главное что б пароль был верный) то через несколько минут прокси просто перестанет пускать игроков и зависнет...

Также то же самое случится при спаме командой /login qwqwqw и включенной двухфакторке (я тестил только с двухфакторкой LimboAuth-SocialAddon, qr полагаю также уязвим)

Решение: добавить кулдауны на команды :)

У себя я это закостылил таким способом:
![image](https://github.com/Elytrium/LimboAuth/assets/47824475/6cd17b32-ca01-47b9-b50f-349b3981b59d)
Плюс ввёл глобальный кулдаун на все команды от прокси

**Comment by Dasssdd** [comment]
Дай ссылку на фикс
