### ISSUE TITLE
[BUG]How to transfer limbo auth database to plugin mc-auth?

### ISSUE THREAD

**Issue by MahadRegent** [Elytrium/LimboAuth#133]
Im sorry,but how to transfer limboauth db to mc-auth pl db.
I buyed nullcordx and i need to transfer to another plugin because limbo auth have issues in that (localhost ip on players)

**Comment by manul694** [comment]
You should ask mc auth devs

**Comment by mdxd44** [comment]
there is a discord server for such a questions, also there is should be a bot for automatic conversion as far as I remember
https://ely.su/discord (not working now, use https://discord.gg/sxVzYv2dbR)
