### ISSUE TITLE
[BUG] Player kick IndexOutOfBoundsException with LuckPerms

### ISSUE THREAD

**Issue by EpicPlayerA10** [Elytrium/LimboAuth#134]
**Describe the bug**
When I have installed both LuckPerms and LimboAuth installed on the proxy and set the option `online-mode-need-auth` to `false`, then when the first player joins to the proxy on client 1.20.4 then he get kicked immediately from the server for `Internal Exception: java.lang.IndexOutOfBoundsException: Index 24 out of bounds for length 9`. When that first player joined and got kicked, then the next ones don't get kicked.

Tested clients:
- 1.20.4
- 1.20.2

**To Reproduce**
1. Setup velocity proxy and backend server
2. Install LimboAuth, LimboAPI and LuckPerms
3. In the LimboAuth config set the option `online-mode-need-auth` to `false`
4. Start the proxy
5. Join to the server using premium account
6. See kick message

Subsequent players are not kicked from the server. You need to restart it to get kicked again.

**Expected behavior**
The player should not get kicked

**Screenshots**
![image](https://github.com/Elytrium/LimboAuth/assets/62206933/04fc2d78-5f80-4ca5-aac4-a0752e49c033)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.1.18, downloaded from https://github.com/Elytrium/LimboAPI/releases/download/1.1.18/limboapi-1.1.18.jar
 - LimboAuth 1.1.14-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAuth/releases/download/dev-build/limboauth-1.1.14-SNAPSHOT.jar

 - /velocity dump link [velocity-dump-2023-12-26-13-00-44.json](https://github.com/Elytrium/LimboAuth/files/13771224/velocity-dump-2023-12-26-13-00-44.json)

**Additional context**

**Comment by EpicPlayerA10** [comment]
I discovered a workaround for that bug. You need to set the option in config `main.mod.enabled` to `false` and the bug disappears.

**Comment by hevav** [comment]
I think it's some kind of race condition bug when the client switches the Config/Play protocol state. Perhaps we need to implement a new method in Perhaps we need to implement a new method in LimboAPI LimboSessionHandler or make onSpawn run after a successful protocol state switch.
