### ISSUE TITLE
[BUG] clients display errors when entering commands

### ISSUE THREAD

**Issue by XenWayne** [Elytrium/LimboAuth#14]
**Describe the bug**
in high version minecraft , clients display errors when entering commands，that may results from permissions issue.
the command works, but the warning seems weird.

**To Reproduce**
1.enter the velocity server
2. input in game 'login or register commands'
3. See error

**Expected behavior**
The commands should be in white color without warnings and it's better to have command prompt.

**Screenshots**
![image](https://user-images.githubusercontent.com/54123699/158585517-72e96ced-a174-4aac-876e-90513df8e327.png)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - [LimboAPI 1.0.3, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]
 - [LimboAuth 1.0.3-rc3, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]

 - /velocity dump link [https://dump.velocitypowered.com/vinadilepa.json](https://dump.velocitypowered.com/vinadilepa.json)

**Additional context**
I am not good at English,and if there are sth which can't be expressed well,i am sorry.

**Comment by mdxd44** [comment]
Update limboapi and limboauth.

https://github.com/Elytrium/LimboAPI/actions/runs/1926762894
https://github.com/Elytrium/LimboAuth/actions/runs/1806267878
