### ISSUE TITLE
[ENHANCEMENT]  support velocity-3.3.0-SNAPSHOT-343

### ISSUE THREAD

**Issue by livxbox5** [Elytrium/LimboAuth#140]
Please update all your plugins to the velocity-3.3.0-SNAPSHOT-343 core and above
![limboauth](https://github.com/Elytrium/LimboAuth/assets/76809274/80f76efb-5125-4c97-b9ae-63a16f99cbef)

**Comment by livxbox5** [comment]
пожалуйста обновите всё ваши плагины на ядро velocity-3.3.0-SNAPSHOT-343 и выше

**Comment by UserNugget** [comment]
Try [dev build](https://github.com/Elytrium/LimboAuth/actions/runs/7628443176)
