### ISSUE TITLE
[QUESTION] How to migrate data base from mcAuth to LimboAuth?

### ISSUE THREAD

**Issue by Everts0n** [Elytrium/LimboAuth#149]
**Additional context**
mcAuth if needed - https://www.spigotmc.org/resources/mc-auth-with-social-link.94870/

**Comment by mdxd44** [comment]
ask in discord (https://ely.su/discord/), as i remember there's a bot that can convert it for you

**Comment by seetch** [comment]
> ask in discord (https://ely.su/discord/), as i remember there's a bot that can convert it for you

reopen issue again, bot is not working for what day.

**Comment by mdxd44** [comment]
you can run it by yourself
https://github.com/Elytrium/DatabaseMigrator3000
