### ISSUE TITLE
[BUG] Premium players losing their data

### ISSUE THREAD

**Issue by Askarionn** [Elytrium/LimboAuth#15]
**Describe the bug**
My configuration: https://pastebin.com/M2nBQHuw
So i configure the plugin when a premium player join he doesn't need to register. The problem is randomly they connected on the server and the system doesn't recognize them as "Premium Players" and changed their UUID and they have to register. To fix the problem all i have to do is remove the specific player form LimboAuth Database but it's happen with A LOT of premium players and it's really annoying.

**To Reproduce**
1. Not sure, it's happen randomly

**Expected behavior**
-

**Screenshots**
-

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAuth 1.0.4 Snapshop downloaded from https://github.com/Elytrium/LimboAuth/actions/runs/1745448894
 - LimboAPI 1.0.3 latest

 - Velocity Dump in private: noiraksA#9930

**Additional context**

**Comment by hevav** [comment]
I'm sorry for the late reply.
As far as I got it, your server has a bad internet connection, causing the Mojang API to respond incorrectly.
You can try either modifying the ``ispremium-auth-url`` parameter or changing your ISP/Hosting Provider.

**Comment by Askarionn** [comment]
Not sure if the problem is with internet connection, we're using Hetzner servers.
We also tried with other premium login plugins and had no problem.
Also, i tried to update to latest Actions Build and it doesn't detect any premium account anymore, i have to downgrade to this version: https://github.com/Elytrium/LimboAuth/actions/runs/1745448894

**Comment by Gracv** [comment]
I have same issue

**Comment by Askarionn** [comment]
> I can reproduce this bug. It only happens on cloudflare api.

for me it happened with mojang api too
