### ISSUE TITLE
[ENHANCEMENT] addon

### ISSUE THREAD

**Issue by Dancbeunny98** [Elytrium/LimboAuth#150]
**Describe the feature you'd like to have implemented**
Добавить возможность или подсказать, каким образом мы можем сделать аддон для данного плагина, который будет заменять некоторые переменные на нужные нам в аддоне. 

**Is your feature request related to an existing problem? Please describe.**
В данный момент у нас имеется переписанный плагин который полностью сломан по структуре для работы по API для связки сайта, так-же создается временные данные в виде мусора чтобы не создавать пользователей которые не прошли регистрацию на сайте. Нам нужно банально сделать аддон чтобы получать обновления оригинального плагина без патчей и исправлений поверх.
**Additional context**
discord: dancebunny98

**Comment by mdxd44** [comment]
ничего не понял

**Comment by Dancbeunny98** [comment]
> ничего не понял

Что не понятного? Сделать аддон для LimboAuth возможно?

**Comment by mdxd44** [comment]
ну у LimboAuth есть апи, на котором работает social addon, вопрос в том что значит "заменять некоторые переменные"

**Comment by Dancbeunny98** [comment]
> ну у LimboAuth есть апи, на котором работает social addon, вопрос в том что значит "заменять некоторые переменные"

![image](https://github.com/Elytrium/LimboAuth/assets/37336183/97284193-4645-40aa-b535-5410f73cd4cf)

**Comment by mdxd44** [comment]
то есть нужен ивент чата? в таком случае возникает проблема безопасности, в версии 2.0.0 я хочу избавиться от передачи чистого пароля в ивенты, и вместо этого передавать AuthSession из которого можно будет получить некоторые данные по типу LimboPlayer и данные игрока из базы

**Comment by Dancbeunny98** [comment]
> то есть нужен ивент чата? в таком случае возникает проблема безопасности, в версии 2.0.0 я хочу избавиться от передачи чистого пароля в ивенты, и вместо этого передавать AuthSession из которого можно будет получить некоторые данные по типу LimboPlayer и данные игрока из базы

Нам необходимо для реализации аддона для связки с сайтом через REST API. Наш аддон будет брать обработчики с LimboAuth а уже наш плагин непосредственно работать в качестве связки с сайтом. менеджером паролей и 2fa у нас будет участвовать сайт.

**Comment by Dancbeunny98** [comment]
Аддон сделан и работает в связке с Invision Community 4
