### ISSUE TITLE
How do I remove a Premium Player and make him back to offline mode?

### ISSUE THREAD

**Issue by Angel-Test1** [Elytrium/LimboAuth#16]
Once someone does /premium, he can't view his skin and /unregister gives an error. Can someone tell how do I rewind /premium?

**Comment by hevav** [comment]
As for the skin issue, it is fixed in the latest dev-build, which you can download from the Actions tab there
Use ``/forceunregister <nickname>`` to unregister the player

Please, don't use the issues tab for questions, it is better to ask them on our Discord server: https://elytrium.net/discord
