### ISSUE TITLE
Does not work /premium

### ISSUE THREAD

**Issue by kompot7** [Elytrium/LimboAuth#170]
Hello, I have a problem with the /premium team. How can I connect it to all servers? I have Luckperms-velocity, I have given the necessary rights to premium, but it is not available on paper servers. What to do?

**Comment by kompot7** [comment]
here is the LimboAuth configuration, if there are no other authorizations, only LimboAuth
[limboauth.zip](https://github.com/user-attachments/files/16300961/limboauth.zip)

**Comment by kompot7** [comment]
help, up!

**Comment by mdxd44** [comment]
do you use the same luckperms db either on proxy and paper servers?

**Comment by kompot7** [comment]
no
