### ISSUE TITLE
[ENHANCEMENT] hope reconnect can tips login

### ISSUE THREAD

**Issue by 8MiYile** [Elytrium/LimboAuth#173]
Because if I go in on the server side without going through the login instructions it causes an error
So I need a way to reconnect that prompts for the login command

Velocity Dump
https://mclo.gs/DV4RKjn

Logs
https://mclo.gs/j7L6Bg9

**Comment by mdxd44** [comment]
limboapi and via* plugins are incompatible

**Comment by 8MiYile** [comment]
@mdxd44 so why not try fix it?

**Comment by mdxd44** [comment]
i guess this is impossible, and i believe it doesn't make sense anyway
just install these plugins on the backend servers

**Comment by 8MiYile** [comment]
We've made it a habit to put protocol plugin, authentication plugin, and portal-related stuff at the Velocity level, just in case there's any surprises, but also for consistency.
