### ISSUE TITLE
[BUG] incompatible with Raknetify

### ISSUE THREAD

**Issue by Redappleyyds** [Elytrium/LimboAuth#176]
**Describe the bug**
I cannot use Raknetify(https://github.com/RelativityMC/raknetify) When added LimboAuth Plugin

**To Reproduce**
1. Config is Default
2. Join the server using Raknetify
3. See error

**Expected behavior**
I can join my server with Raknetify

**Screenshots**
![image](https://github.com/user-attachments/assets/f41bb9c2-fbea-49ad-94b6-7f3b43cdd282)

**Server Info (please complete the following information):**
 - limboauth-1.1.14.jar
 - Velocity 3.3.0-SNAPSHOT

**Additional context**
nope

**Comment by CamperSamu** [comment]
This is an issue with LimboAPI and this is technically both a wrong and duplicate issue: https://github.com/Elytrium/LimboAPI/issues/61
