### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Viskozm** [Elytrium/LimboAuth#183]
Невозможно пользоваться командой /changepassword

Выдал permission limboauth.commands.changepassword
В конфиге стоит # Permission: limboauth.commands.changepassword
    change-password: PERMISSION
В настройках велосити стоит Velocity (velocity.toml) нужно поставить true перед параметром announce-proxy-commands
LuckPerms на велосити и на основном сервере установлен.
В чем дело?

**Comment by sub-kek** [comment]
Можно информацию /velocity dump хотя-бы

**Comment by Viskozm** [comment]
> либо настрой luckperms, либо поставь в конфиге `change-password: TRUE`

Так я поставил permission в LuckPerms и все равно не существует команды

**Comment by mdxd44** [comment]
значит ставил в /lp, а не в /lpv
либо используй одну базу, либо выдавай через /lpv
