### ISSUE TITLE
[BUG] If you use /license or /premium, you can't chat

### ISSUE THREAD

**Issue by DreamMiu** [Elytrium/LimboAuth#188]
**Describe the bug**
Unable to speak after passing advanced certification！

**To Reproduce**
1./reg password password
2. Speak normally
3. Log out of the server with /premium and then join the server. The post will look like a screenshot

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/c7580925-fd01-4081-bdf4-b5b1fc91f7bb)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
limboapi-1.1.27.jar
limboauth-1.1.14-SNAPSHOT.jar

[velocity-dump-2024-12-29-07-02-23.json](https://github.com/user-attachments/files/18267942/velocity-dump-2024-12-29-07-02-23.json)

**Additional context**

**Comment by hevav** [comment]
Install https://modrinth.com/plugin/signedvelocity

**Comment by DreamMiu** [comment]
> 安装https://modrinth.com/plugin/signedvelocity

After installing this plugin is the same, same error

**Comment by DreamMiu** [comment]
To find a solution, installation: https://github.com/TrPlugins/TrChat can normal chat
