### ISSUE TITLE
[BUG] Login Error

### ISSUE THREAD

**Issue by Garuda2703** [Elytrium/LimboAuth#24]
**Describe the bug**
Anyone that join the server get kicked and "Disconnected" message appear

**To Reproduce**
1. Install limboauth and limboapi
2. connect to the server
3. See error

**Expected behavior**
User can successfully connect to the server

**Screenshots**
![image](https://user-images.githubusercontent.com/60492345/162560777-99fe9d0a-95dc-4fbc-afae-2782b562eba9.png)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - [LimboAPI 1.0.4-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/2082878209]
 - [LimboAuth 1.0.4-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAuth/actions/runs/2086353707]

 - /velocity dump link [https://dump.velocitypowered.com/uwefasagoh.json]

**Additional context**
None

**Comment by hevav** [comment]
Modify ``limboapi/config.yml`` and set ``max-prepare-version: LATEST`` there

**Comment by Garuda2703** [comment]
okay imma try that

**Comment by Garuda2703** [comment]
theres no `max-prepare-version: LATEST` on the limboapi config so i just added it and i still get the same error

**Comment by hevav** [comment]
There is
![Screenshot_20220409-100748_Termius.jpg](https://user-images.githubusercontent.com/14876058/162560999-87f0b2bb-51c1-4090-89f1-67c056457661.jpg)

**Comment by Garuda2703** [comment]
oh yeah i just see that and set that to the latest, it works thank you!
