### ISSUE TITLE
[BUG] Проблемы с подключением MySQL базы данных

### ISSUE THREAD

**Issue by ASergeev69** [Elytrium/LimboAuth#25]
При подключении плагина к базе данных выдаёт следующую ошибку - https://pastebin.com/yxDiK8Kf
Как я понял связанно как-то с размером строк или что-то такое, при импорте базы говорит:
"Указан слишком длинный ключ. Максимальная длина ключа составляет 767 байт"

**Comment by hevav** [comment]
https://stackoverflow.com/questions/1814532/mysql-error-1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by mdxd44** [comment]
Видимо проблема была решена.
