### ISSUE TITLE
[ENHANCEMENT] Добавление команды /logout

### ISSUE THREAD

**Issue by Snoop1CattZ69** [Elytrium/LimboAuth#29]
Отсутствует команда /logout закрывающую сессию игрока.

Понятно что не каждый этим пользуется, однако в некотором случае нужная функция.

Можно добавить в конфиг опцию которая выключает сохранении сессии и при каждом заходе будет требовать пароль + добавить всё и саму команду /logout

**Comment by Snoop1CattZ69** [comment]
Банальный пример: Играют два брата с разных компов, у них один айпи т.к раздача сети по роутеру, один захотел насолить другому, дождался когда тот выйдет из сети, заходит под его ником, а сессия сохранена, итог: Братья подрались, а на админов быканули за то что нет безопасности от плохих братьев :)

**Comment by hevav** [comment]
Скоро добавлю возможность добавить свои алиасы
