### ISSUE TITLE
/premium password confirm

### ISSUE THREAD

**Issue by Watghi** [Elytrium/LimboAuth#3]
Why is offline uuid not deleted after linking the account to premium uuid?
![image](https://user-images.githubusercontent.com/95087767/150672885-6394ac7c-ba5e-450a-8963-add6682c8058.png)

LimboAuth latest version
online-mode-need-auth: false

**Comment by hevav** [comment]
In most cases offline uuid should NOT be deleted. That's not a bug. If you don't want to restore UUID from the database, just turn off the ``safe-uuid`` parameter

**Comment by Watghi** [comment]
Just because of this, an error occurs in the console, as well as in the chat when I try to enter /2fa enable gtses23.
![image](https://user-images.githubusercontent.com/95087767/150673215-0fc2978b-fc35-4f46-81f5-7e2f3d7ab14f.png)

**Comment by hevav** [comment]
Okay, 2FA should be force-disabled for /premium players. I'll make an update, where the plugin will send the error message about impossibility to set 2FA on accounts without password.

**Comment by Watghi** [comment]
not only 2fa, all teams that somehow interact on a premium player account

**Comment by hevav** [comment]
I got it
