### ISSUE TITLE
[BUG] Сообщения в чате не отображаются на 1.19

### ISSUE THREAD

**Issue by melzyy** [Elytrium/LimboAuth#34]
Пробовал на пустом конфиге велосити и лимбо плагинов
/velocity dump --> https://dump.velocitypowered.com/aterebiliz.json
На 1.18.2 все видно на том же запущеном сервере

Версия плагинов последняя из релизов
![image](https://user-images.githubusercontent.com/71926357/172839360-96ed5614-349a-4cab-89c2-97cb43a94091.png)

**Comment by moderator10000078** [comment]
в настройках майна защищённый чат и подобная хуета офнута?

**Comment by melzyy** [comment]
> 

![image](https://user-images.githubusercontent.com/71926357/172840824-0c356562-daae-47d2-a571-8718ed22542f.png)
ну вроде

**Comment by melzyy** [comment]
только что пересобрал с сурса велосити, та же проблема
ну чтож, тогда буду ждать фикс с их стороны

**Comment by melzyy** [comment]
на крайнем билде починили, закрываю

**Comment by Z1xus** [comment]
Я использую последний билд Velocity и всё ещё испытываю проблемы с чатом. Ещё newline заполнитель сломан: 
![image](https://user-images.githubusercontent.com/40185941/173347623-2364bc03-05c5-4c10-9c97-cb3446e8f124.png)

**Comment by hevav** [comment]
Последний билд не велосити, а LimboAuth + LimboAPI

**Comment by hevav** [comment]
Для \n надо использовать {NL}

**Comment by Z1xus** [comment]
{NL} используется

**Comment by Z1xus** [comment]
Спасибо
