### ISSUE TITLE
[BUG] Account authentication issues 

### ISSUE THREAD

**Issue by LatosProject** [Elytrium/LimboAuth#37]
**Describe the bug**
I want to enable the online and offline authentication functions of limboauth. and I set the "online-mode-need-auth" in the configuration file to false. However, when an offline player enters the server, the client prompts "failed to log in:invalid session." I confirm that I have turned off the "online-mode" function of spigot and velocity
**To Reproduce**
1. Offline players enter the server

**Expected behavior**
Offline players and online players successfully enter the server, and online players do not need to authenticate their accounts

**Screenshots**
![Screenshot_20220614_014319_com tungsten hmclpe](https://user-images.githubusercontent.com/89125260/173414213-1b5fe782-703f-4565-8d7b-2faaa94cf45c.jpg)
![Screenshot_20220614_015306](https://user-images.githubusercontent.com/89125260/173414568-1df6ff3f-e4bf-48a9-9d25-50cd223f6bb6.jpg)

**Server Info (please complete the following information):**
 LimboAPI 1.0.6
 LimboAuth 1.0.6

**Additional context**

**Comment by hevav** [comment]
It is impossible to check if the player is premium-moded or not
It is only possible to check if the player's nickname is premium-moded
So with the online-mode-need-auth setting set to false cracked players will see this error if the nickname is premium-moded

**Comment by LatosProject** [comment]
> It is impossible to check if the player is premium-moded or not It is only possible to check if the player's nickname is premium-moded So with the online-mode-need-auth setting set to false cracked players will see this error if the nickname is premium-moded

i see,thank you

> It is impossible to check if the player is premium-moded or not It is only possible to check if the player's nickname is premium-moded So with the online-mode-need-auth setting set to false cracked players will see this error if the nickname is premium-moded

I see, thank you

**Comment by LatosProject** [comment]
> It is impossible to check if the player is premium-moded or not It is only possible to check if the player's nickname is premium-moded So with the online-mode-need-auth setting set to false cracked players will see this error if the nickname is premium-moded

I see, thank you
