### ISSUE TITLE
Do not remove premium account passwords from database

### ISSUE THREAD

**Issue by MegalithOffical** [Elytrium/LimboAuth#39]
Hello i use MYSQL database and my Site also connected to same database when my players use /premium command the plugin delete's password from database thats why my players couldnt login from site. how can i fix that ?

**Comment by ArtifactyNight** [comment]
Same issue here
It's have problem with my webshop

**Comment by moderator10000078** [comment]
I think it's worth writing to the developer so that he adds a function to the config that does not delete the password from the database when enabled /premium

**Comment by SenPr** [comment]
this honestly shouldn't be to hard to change. If you're willing to compile the plugin yourself

**Comment by TheSidOffical** [comment]
moderator10000078, you are right there should be more Options about Database utilitys and settings.

**Comment by hevav** [comment]
Duplicate of #23
