### ISSUE TITLE
[BUG] If forced to use offline UUID, my online skin will not be displayed and cannot be moved after logined

### ISSUE THREAD

**Issue by g2nnyS** [Elytrium/LimboAuth#4]
After I turn on option "force-offline-uuid",my online skin not be display, cannot be moved
But if I close "force-offline-uuid" my data stored on the offline UUID will be lost
（my velocity server have SkinsRestorer）

**Comment by hevav** [comment]
Use latest dev build

**Comment by g2nnyS** [comment]
I have used the latest dev build(1.0.3)

**Comment by hevav** [comment]
That is a release build. Use one from Actions tab.

**Comment by g2nnyS** [comment]
The problem of Cannot be moved still exists

**Comment by g2nnyS** [comment]
Offline accounts can be moved after logging in, online accounts cannot
