### ISSUE TITLE
[BUG] /changepassword Не работает

### ISSUE THREAD

**Issue by exosmium** [Elytrium/LimboAuth#40]
**Описание**
Смена пароля в игре для игроков не работает.

**Конкретнее**
1. Вводишь команду /changepassword [пароль] [пароль]
2. В чат выбрасывает ошибку "Incorrect argument for command at position..."

**Должно было быть**
Пароль должен был смениться.

**Скрины**
![2022-06-25_13 32 01](https://user-images.githubusercontent.com/59437511/175769822-8253e9d8-2254-4e4e-9f43-622e9e784a72.png)

**Информация**
 - Все плагины лимбо (Авторизация, фильтр и API) 1.0.5 версии.

 - Дамп велосити: https://dump.velocitypowered.com/yiyimifoqe.json

**Comment by hevav** [comment]
Поставь LuckPerms Velocity

**Comment by exosmium** [comment]
> Поставь LuckPerms Velocity

Я не хочу нагружать велосити, мне там от лакпермса вообще смысла нет. Неужели нет других вариантов?

**Comment by hevav** [comment]
Вариант есть - любой другой плагин на права для прокси

**Comment by exosmium** [comment]
То есть возможности / планов это пофиксить не имеется? Просто на том же MoonVkAuth / DskAuth все работало и без плагинов на права. Тем более причем тут права, если просто строчку в бд изменить надо...

**Comment by mdxd44** [comment]
Если нет прав на команду, то она для игрока не существует. Как связано отсутствие прав на команду и изменение строки в бд?

**Comment by exosmium** [comment]
Понял, если дело в правах тогда ещё ладно. Хотелось бы только более подробное описание плагина со всеми правами и чтобы писало про права, а не про "Incorrect Usage". Надеюсь будет возможность добавить 🙂

**Comment by MrArtur4Ik** [comment]
В конфиге LimboAuth ищем поле command-permission-state и под ним поле change-password
Напротив него вместо PERMISSION ставим TRUE
