### ISSUE TITLE
[BUG] Offline players can't login 

### ISSUE THREAD

**Issue by g2nnyS** [Elytrium/LimboAuth#5]
I found that closed "online-mode-need-auth" after. Offline players can't login.
A little Offline players can login in after waiting for a while another player still can't login
it shows:"fail login,invalid session"
![image](https://user-images.githubusercontent.com/72686586/153371445-8672d64c-d530-4a21-9be0-92e0c003f454.png)

**Comment by hevav** [comment]
It is intended that in this mode offline players cannot join with premium nicknames.

**Comment by g2nnyS** [comment]
But he never used a premium account to login

**Comment by hevav** [comment]
But his nickname belongs to one's premium account

**Comment by g2nnyS** [comment]
I would like to ask if this can be solved?
Because many members on my server have offline ID that correspond to their online account ID

**Comment by hevav** [comment]
Turn on that mode, ask players to manually enter the /premium command
