### ISSUE TITLE
[ENHANCEMENT] Add 1.19.2 support

### ISSUE THREAD

**Issue by MineForce899** [Elytrium/LimboAuth#50]
**Describe the feature you'd like to have implemented**
Add support for 1.19.2

**Is your feature request related to an existing problem? Please describe.**
When players try to join through 1.19.2, they get kicked

**Comment by hevav** [comment]
1.19.2 support is already implemented. Update plugins

**Comment by MineForce899** [comment]
I am on latest version (1.0.5-jdk17)

**Comment by hevav** [comment]
1.0.6 is the latest.

**Comment by AVuTuVA** [comment]
use dev build 1.0.6-snapshot
