### ISSUE TITLE
[BUG] 1.8 Clients can't join 1.19.2 servers

### ISSUE THREAD

**Issue by CamperSamu** [Elytrium/LimboAuth#52]
**Describe the bug**
Everytime I try to connect to a 1.19.2 server via limboauth the client crashes due to packet errors.

**To Reproduce**
1. Setup a 1.19.2 server and a proxy with LimboAuth
2. Try to join
3. See error

**Expected behavior**
I should be able to join without any problems

**Screenshots**
![Example Crash](https://user-images.githubusercontent.com/32773961/190867481-c813977b-48d0-4a83-8383-94c99ae71a5b.png)
_Example Crash_

**Server Info (please complete the following information):**
 - LimboAPI and LimboAuth 1.0.6
 - Limbo Api Social Addon 1.0.2
 - Other plugins: floodgate, geyser, luckperms, minimotd-velocity, skinsrestorer, velocity_tools, viaversion, viabackwards, viarewind

 - [/velocity dump](https://dump.velocitypowered.com/awuvojumuh.json)

**Comment by AVuTuVA** [comment]
delete viaversion, viabackwards, viarewind and install in the server

**Comment by CamperSamu** [comment]
I need them on the proxy for modern forwarding
