### ISSUE TITLE
[ENHANCEMENT] Update H2 database to 2.x

### ISSUE THREAD

**Issue by skbeh** [Elytrium/LimboAuth#54]
**Describe the feature you'd like to have implemented**
Update h2 database library to version 2.x and perhaps also implement auto migration.

**Is your feature request related to an existing problem? Please describe.**
I had bad experience with h2 database 1.x because of its risk of database corruption. The 1.x version is not recommend by its developer anymore.
There are more details in the following link.

**Additional context**
https://github.com/LuckPerms/LuckPerms/issues/3458

**Comment by hevav** [comment]
We haven't updated it yet only because we need to implement auto migration.
We didn't know that there might be a risk of corruption, so we'll try to implement it faster
