### ISSUE TITLE
[BUG] Where can I find the permits?

### ISSUE THREAD

**Issue by puritynetwork** [Elytrium/LimboAuth#57]
I can't find the permissions to give users

**Comment by danieleguglietti** [comment]
https://github.com/Elytrium/LimboAuth/tree/master/src%2Fmain%2Fjava%2Fnet%2Felytrium%2Flimboauth%2Fcommand

In each class in hasPermission method

**Comment by puritynetwork** [comment]
Thank you

**Comment by JNNGL** [comment]
https://surnin-vladislav.gitbook.io/elytrium/limboauth/permissions-and-commands
