### ISSUE TITLE
[BUG] Error after player log in

### ISSUE THREAD

**Issue by Dagrond** [Elytrium/LimboAuth#76]
Versions: ALL LATEST: Limboauth, limboapi, limbofiler and Velocity.
Just updated all to latest version, now if someone is login using password there is an error in console:
![image](https://user-images.githubusercontent.com/30177675/216914390-75176904-0789-4084-99bc-84acfb66dd19.png)

**Comment by mdxd44** [comment]
if this is still happens please reopen an issue (this one probably was caused due to mod.enable: true without setting mod.verify-key)
