### ISSUE TITLE
How to convert Authme's database to LimboAuth's database？

### ISSUE THREAD

**Issue by 485957018** [Elytrium/LimboAuth#77]
I changed from Authme to LimboAuth, but I will not convert the database data

**Comment by manul694** [comment]
INSERT INTO limbo.AUTH SELECT realname, username, COALESCE(password, ""), COALESCE(ip, ""), COALESCE(totp, ""), regdate, "", "" FROM authme.table WHERE username IS NOT NULL;

**Comment by mdxd44** [comment]
there is a discord server for such a questions, also there is should be a bot for automatic conversion as far as I remember
https://ely.su/discord (not working now, use https://discord.gg/sxVzYv2dbR)
