### ISSUE TITLE
Добавить возможность добавлять кликабельные ссылки и повторное оповещение

### ISSUE THREAD

**Issue by kzdnl** [Elytrium/LimboAuth#78]
На данный момент ссылка в конфиге не кликабельная для игрока, возможно ли это исправть? link-cmd-usage:

А также сделать, чтобы приходило автоматическое сообщение о том, что игроку стоит привязать аккаунт к соц-сети!

**Comment by hevav** [comment]
Кликабельные ссылки можно через minimessage
Автоматическое сообщение о том что игроку стоит привязать соцсеть ставится в конфиге

**Comment by kzdnl** [comment]
Интервал для автосообщения задать нельзя?
