### ISSUE TITLE
[BUG] Players with short names get kicked even though its within the regex

### ISSUE THREAD

**Issue by Synkstar** [Elytrium/LimboAuth#99]
**Describe the bug**
When you are a cracked player and your name is too short you are kicked for "You are not logged into your Minecraft account. If you are logged into your Minecraft account, try restarting your Minecraft client."

**To Reproduce**
Use the attached config file and then set your name to something like Yazi and try to join the server using a cracked client. But if your name is longer like Yaziman you wont get kicked.

**Expected behavior**
Should allow you to join and set a password like normal.

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.1.12
 - Limboauth 1.1.12
 - LimboFilter 1.1.10

My config. DB and mod verify key stripped ofc: https://gist.github.com/Synkstar/0b4edef1cb760b51d3e28f1483ef5fa9

Thanks.

**Comment by hevav** [comment]
Not a bug.
You've misunderstood what ``online-mode-need-auth: false`` config option does.

**Comment by Synkstar** [comment]
Is it possible to do true hybrid auth where a cracked player can have the same name as a premium account but just have the prefix on the nickname? 

Another alternative is to make it have a kick message saying a premium player has this username already instead of them just getting timed out.

I wanted to have my server be where premium just joins and has no prefix and doesn't need a password. But the cracked players just have a $ in their name.
